steps:
- script: dotnet restore -v minimal src/VoltstroEngine.sln
  displayName: Dotnet Restore
    
- script: dotnet build src/VoltstroEngine.sln --no-restore -c $(buildConfiguration)
  displayName: Dotnet Build