trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure/checkout.yml
  - template: azure/build.yml
  - template: azure/test.yml